#!/bin/bash
#
# An "orchestration" script for observing/folding/filterbanking
#  pulsars--designed speciically for the ATA Gnu Radio environment
#  which uses a pair of USRP N320s
#
# It sets parameters (some automagically), then calls
#  "stupid_simple_pulsar" underneath the covers.
#
#
export PSRCAT_FILE=/usr/local/share/psrcat.db

#
# Echo what we're running to the console--for sanity checking
#
function echorun
{
	echo running: $*
	$*
}

#
# Determine MJD for filename purposes
#
MJD=`python2 -c "import time; print '%-8.2f' % ((time.time()/86400.0)+40587.0)"`

#
# Establish parameter defaults
#
NAME=j0332+5434
PERIOD=0.714520
WIDTH=0.0066
RATE=10e6
FREQ=629.0e6
SKY=611.0e6
ANTENNA=TX/RX
DM=26.76
WHICH_USRP=0
OBSTIME=1800
GAIN=20
MASK=None
SUBDEV="A:0"
DEC=54.5
RA=3.5
DPY=0
cat >hlp$$ <<!EOF!
--name                   Set pulsar name. Default: $NAME
--period|p0              Set period (seconds). Default: $PERIOD
--width|w50              Set pulse width (seconds).  Default: $WIDTH
--rate                   Set sample-rate (Hz).    Default: $RATE
--freq|--frequency       Set tuner frequency (Hz).  Default: $FREQ
--sky                    Set sky frequency (Hz).    Default: $SKY
--antenna|--ant          Set USRP antenna port (RX2 or TX/RX) Default: $ANTENNA
--which|--usrp           Set which USRP to use.  Default: $WHICH_USRP
--dm                     Set dispersion measure. Default $DM
--obstime|--time         Set observation time (seconds). Default: $OBSTIME
--gain                   Set RF gain. Deault; $GAIN
--mask|--rfi             Comma-separated list of RFI freqs (Hz).
--subdev                 USRP sub=device (A:0, etc).  Default $SUBDEV
--display                ENABLE real-time display
!EOF!
#
# Parse command line
#
while [ $# -ge 1 ]
do
	case $1 in
	  --name)
	      NAME=$2
	      shift 2
	      ;;
	  --period|p0)
	      PERIOD=$2
	      shift 2
	      ;;
	   --width|w50)
	      WIDTH=$2
	      shift 2
	      ;;
	   --rate)
	     RATE=$2
	     shift 2
	     ;;
	   --freq|--frequency)
	     FREQ=$2
	     shift 2
	     ;;
	
	    --sky)
	      SKY=$2
	      shift 2
	      ;;
	    --which|--usrp)
	      WHICH_USRP=$2
	      shift 2
	      ;;
	    --antenna|--ant)
	      ANTENNA=$2
	      shift 2
	      ;;
	    --dm)
	      DM=$2
	      shift 2
	      ;;
	    --obstime|--time)
	      OBSTIME=$2
		  shift 2
		  ;;
		--gain)
		  GAIN=$2
		  shift 2
		  ;;
		--mask|--rfi)
		  MASK=$2
		  shift 2
		  ;;
		--subdev)
		  SUBDEV=$2
		  shift 2
		  ;;
		 --help)
		 cat hlp$$
		 rm -f hlp$$
		 exit
		 ;;
		 --display)
		 DPY=1
		 shift
		 ;;
	    *)
	    echo "Unknown argument: $1"
	    exit
	 esac
done
rm -f hlp$$
#
# IF new USRPs are added they can be enumerated here
#
case $WHICH_USRP in
	0|usrp0)
	    ADDR=10.11.2.61
	    ;;
	1|usrp1)
	    ADDR=10.11.2.71
	    ;;
	*)
	echo "Unknown USRP: $WHICH_USRP"
	exit
	;;
esac

#
# Now try to lookup the pulsar in the database
#
SPINPREDICT=0
psrcat -c DM -nohead -nonumber -o short $NAME|grep 'not in catalog' >tst.$$
if [ ! -s tst.$$ ]
then
SPINPREDICT=1
DM=`psrcat -c DM -nohead -nonumber -o short $NAME`
F0=`psrcat -c F0 -nohead -nonumber -o short $NAME`
PERIOD=`python2 -c "print '%.13f' % (1.0/$F0)"`
WIDTH=`psrcat -c W50 -nohead -nonumber -o short $NAME`
WIDTH=`python2 -c "print $WIDTH/1000.0"`
DEC=`psrcat -c DECJ -nohead -nonumber -o short $NAME|sed -e 's/+//'`
RA=`psrcat -c RAJ -nohead -nonumber -o short $NAME`
DEC=`echo $DEC|awk '
/./ {split($0,ta,":")
	 sgn = 1.0
	 if (ta[1] < 0) {
		 ta[1] *= -1
	     sgn = -1.0
	 }
	 hrs = ta[1]
	 hrs += ta[2]/60.0
	 hrs += ta[2]/3600.0
	 hrs *= sgn
	 printf ("%5.2f", hrs)
}'`
RA=`echo $RA|awk '
/./ {split($0,ta,":")
	 sgn = 1.0
	 if (ta[1] < 0) {
		 ta[1] *= -1
	     sgn = -1.0
	 }
	 hrs = ta[1]
	 hrs += ta[2]/60.0
	 hrs += ta[2]/3600.0
	 hrs *= sgn
	 printf ("%5.2f", hrs)
}
'`
else
	echo Pulsar $NAME not found in PSRCAT
	echo USING DEFAULT VALUES
fi
rm -f tst.$$

if [ $SPINPREDICT -eq 1 ]
then
	#
	# Pull ephemera out of psrcat/TEMPO2 in .par format
	#
	skym=`python2 -c "print '%d' % int($SKY/1.0e6)"`
	psrcat -db_file /usr/local/share/psrcat.db -e2 $NAME |grep -v ELONG|grep -v ELAT >par$$.par 2>/dev/null
	echo "TZRMJD               $MJD" >>par$$.par
	echo "TZRSITE              ATA" >>par$$.par
	echo "TZRFREQ              $skym" >>par$$.par

	lc=`cat par$$.par|wc -l`
	if [ $lc -gt 5 ]
	then
		PERIOD=`spin_predict $MJD $skym par$$.par`
		rm -f par$$.par
		
		echo PERIOD calculated as $PERIOD
	fi
fi
#
# We KNOW that we're using one of a pair of USRP N32x on the gnuradio1
#   server @ ATA/HCRO
#
DEVICE="addr=$ADDR,type=n3xx,product=n320,master_clock_rate=200e6"

#
# Invoke
#
FMASK=""
if [ ! $MASK =  "None" ]
then
   FMASK="--fmask $MASK"
else
   FMASK=""
fi
if [ $DPY -ge 1 ]
then
	echo "*******" Starting pulsar profile display tool--there will be a pause before it starts...
	(sleep 10; profile_display --width $WIDTH --period $PERIOD --pname $NAME )&
fi
echorun stupid_simple_pulsar --antenna $ANTENNA --device "$DEVICE" --dm $DM --freq $FREQ --logtime 60 --obstime $OBSTIME \
   --outfile psr-$NAME-$MJD.json --pname $NAME --refclock external --rfgain $GAIN --sky $SKY --srate $RATE \
   --timesrc external --width $WIDTH --period $PERIOD $FMASK --subdev $SUBDEV --fine 1 --ra $RA --dec $DEC
